"""add zone_access_configs table

Revision ID: 69f06f36e1af
Revises: 008_add_allow_same_firewall_push
Create Date: 2026-03-16 19:49:43.345151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69f06f36e1af'
down_revision = '008_add_allow_same_firewall_push'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_access_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_zone', sa.String(length=100), nullable=False, comment='源区域'),
    sa.Column('dest_zone', sa.String(length=100), nullable=False, comment='目的区域'),
    sa.Column('firewall_id', sa.Integer(), nullable=False, comment='防火墙ID'),
    sa.Column('nat_type', sa.String(length=20), nullable=True, comment='NAT类型: SNAT/DNAT/BOTH/None'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置说明'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['firewall_id'], ['firewalls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_access_configs_id'), 'zone_access_configs', ['id'], unique=False)
    op.alter_column('firewalls', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='防火墙名称',
               existing_nullable=False)
    op.alter_column('firewalls', 'type',
               existing_type=postgresql.ENUM('fortigate', 'hillstone', 'leadsec', 'h3c', 'guanqun', 'feita', 'wangshen', 'sangfor', 'huawei', 'shanshi', 'other', name='firewalltype'),
               comment='防火墙类型',
               existing_nullable=False)
    op.alter_column('firewalls', 'management_ip',
               existing_type=sa.VARCHAR(length=50),
               comment='管理IP',
               existing_nullable=False)
    op.alter_column('firewalls', 'connection_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='连接配置(根据type存不同结构)',
               existing_comment='连接配置',
               existing_nullable=True)
    op.alter_column('firewalls', 'internal_protected_ips',
               existing_type=sa.TEXT(),
               comment='内部防护IP段，每行一个',
               existing_comment='防护IP段',
               existing_nullable=True)
    op.alter_column('firewalls', 'external_protected_ips',
               existing_type=sa.TEXT(),
               comment='外部防护IP段，每行一个',
               existing_comment='外部防护IP段',
               existing_nullable=True)
    op.alter_column('firewalls', 'supported_policy_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='支持的策略类型数组',
               existing_comment='支持的策略类型',
               existing_nullable=True)
    op.alter_column('firewalls', 'auto_push',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='是否支持自动推送(0:否, 1:是)',
               existing_comment='是否支持自动推送',
               existing_server_default=sa.text('1'))
    op.alter_column('firewalls', 'allow_same_firewall_push',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               nullable=True,
               comment='是否允许同墙推送（源目的IP都在内部IP段时）(0:否, 1:是)',
               existing_comment='是否允许同墙推送（源目的IP都在内部IP段时）',
               existing_server_default=sa.text('false'))
    op.alter_column('firewalls', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='状态(enabled/disabled)',
               existing_comment='状态',
               existing_server_default=sa.text("'enabled'::character varying"))
    op.alter_column('firewalls', 'is_active',
               existing_type=sa.INTEGER(),
               comment='是否启用(0:否, 1:是)',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('firewalls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('firewalls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_firewalls_id'), 'firewalls', ['id'], unique=False)
    op.alter_column('operation_logs', 'order_id',
               existing_type=sa.INTEGER(),
               comment='工单ID',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型',
               existing_nullable=False)
    op.alter_column('operation_logs', 'operation_detail',
               existing_type=sa.TEXT(),
               comment='操作详情',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operator',
               existing_type=sa.VARCHAR(length=100),
               comment='操作人',
               existing_nullable=True)
    op.alter_column('operation_logs', 'result',
               existing_type=sa.VARCHAR(length=50),
               comment='操作结果(success/failed)',
               existing_nullable=True)
    op.alter_column('operation_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('operation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='操作时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_operation_logs_order_id', table_name='operation_logs')
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.drop_constraint('operation_logs_order_id_fkey', 'operation_logs', type_='foreignkey')
    op.create_foreign_key(None, 'operation_logs', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'order_no',
               existing_type=sa.VARCHAR(length=50),
               comment='工单编号',
               existing_nullable=False)
    op.alter_column('orders', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='工单标题',
               existing_nullable=False)
    op.alter_column('orders', 'description',
               existing_type=sa.TEXT(),
               comment='工单描述',
               existing_nullable=True)
    op.alter_column('orders', 'excel_file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Excel文件路径',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='orderstatus'),
               comment='工单状态',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::orderstatus"))
    op.alter_column('orders', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment='创建人',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_orders_order_no', table_name='orders')
    op.drop_constraint('orders_order_no_key', 'orders', type_='unique')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.alter_column('policies', 'order_id',
               existing_type=sa.INTEGER(),
               comment='工单ID',
               existing_nullable=False)
    op.alter_column('policies', 'firewall_id',
               existing_type=sa.INTEGER(),
               comment='防火墙ID',
               existing_nullable=True)
    op.alter_column('policies', 'source_zone',
               existing_type=sa.VARCHAR(length=100),
               comment='源区域',
               existing_nullable=True)
    op.alter_column('policies', 'dest_zone',
               existing_type=sa.VARCHAR(length=100),
               comment='目标区域',
               existing_nullable=True)
    op.alter_column('policies', 'source_ip',
               existing_type=sa.VARCHAR(length=500),
               comment='源IP',
               existing_nullable=True)
    op.alter_column('policies', 'dest_ip',
               existing_type=sa.VARCHAR(length=500),
               comment='目标IP',
               existing_nullable=True)
    op.alter_column('policies', 'service',
               existing_type=sa.VARCHAR(length=500),
               comment='服务/端口',
               existing_nullable=True)
    op.alter_column('policies', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='动作(permit/deny)',
               existing_nullable=True)
    op.alter_column('policies', 'is_merged',
               existing_type=sa.INTEGER(),
               comment='是否已合并(0:否, 1:是)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('policies', 'merged_policy_id',
               existing_type=sa.INTEGER(),
               comment='合并后的策略ID',
               existing_nullable=True)
    op.alter_column('policies', 'push_status',
               existing_type=sa.VARCHAR(length=50),
               comment='推送状态',
               existing_nullable=True)
    op.alter_column('policies', 'push_result',
               existing_type=sa.TEXT(),
               comment='推送结果',
               existing_nullable=True)
    op.alter_column('policies', 'pushed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='推送时间',
               existing_nullable=True)
    op.alter_column('policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_policies_order_id', table_name='policies')
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.drop_constraint('policies_order_id_fkey', 'policies', type_='foreignkey')
    op.create_foreign_key(None, 'policies', 'orders', ['order_id'], ['id'])
    op.alter_column('policy_versions', 'order_id',
               existing_type=sa.INTEGER(),
               comment='工单ID',
               existing_nullable=False)
    op.alter_column('policy_versions', 'version_type',
               existing_type=sa.VARCHAR(length=20),
               comment='版本类型: original/formatted/user_modified',
               existing_nullable=False)
    op.alter_column('policy_versions', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='策略数据(JSON格式)',
               existing_nullable=False)
    op.alter_column('policy_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policy_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('policy_versions', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='策略数据(JSON格式)',
               existing_nullable=False)
    op.alter_column('policy_versions', 'version_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='版本类型: original/formatted/user_modified',
               existing_nullable=False)
    op.alter_column('policy_versions', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='工单ID',
               existing_nullable=False)
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.create_foreign_key('policies_order_id_fkey', 'policies', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.create_index('idx_policies_order_id', 'policies', ['order_id'], unique=False)
    op.alter_column('policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('policies', 'pushed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='推送时间',
               existing_nullable=True)
    op.alter_column('policies', 'push_result',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='推送结果',
               existing_nullable=True)
    op.alter_column('policies', 'push_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='推送状态',
               existing_nullable=True)
    op.alter_column('policies', 'merged_policy_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='合并后的策略ID',
               existing_nullable=True)
    op.alter_column('policies', 'is_merged',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='是否已合并(0:否, 1:是)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('policies', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='动作(permit/deny)',
               existing_nullable=True)
    op.alter_column('policies', 'service',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='服务/端口',
               existing_nullable=True)
    op.alter_column('policies', 'dest_ip',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='目标IP',
               existing_nullable=True)
    op.alter_column('policies', 'source_ip',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='源IP',
               existing_nullable=True)
    op.alter_column('policies', 'dest_zone',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='目标区域',
               existing_nullable=True)
    op.alter_column('policies', 'source_zone',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='源区域',
               existing_nullable=True)
    op.alter_column('policies', 'firewall_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='防火墙ID',
               existing_nullable=True)
    op.alter_column('policies', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='工单ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.create_unique_constraint('orders_order_no_key', 'orders', ['order_no'])
    op.create_index('idx_orders_order_no', 'orders', ['order_no'], unique=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='orderstatus'),
               comment=None,
               existing_comment='工单状态',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::orderstatus"))
    op.alter_column('orders', 'excel_file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Excel文件路径',
               existing_nullable=True)
    op.alter_column('orders', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='工单描述',
               existing_nullable=True)
    op.alter_column('orders', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='工单标题',
               existing_nullable=False)
    op.alter_column('orders', 'order_no',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='工单编号',
               existing_nullable=False)
    op.drop_constraint(None, 'operation_logs', type_='foreignkey')
    op.create_foreign_key('operation_logs_order_id_fkey', 'operation_logs', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.create_index('idx_operation_logs_order_id', 'operation_logs', ['order_id'], unique=False)
    op.alter_column('operation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='操作时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('operation_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('operation_logs', 'result',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作结果(success/failed)',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operator',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='操作人',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operation_detail',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='操作详情',
               existing_nullable=True)
    op.alter_column('operation_logs', 'operation_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作类型',
               existing_nullable=False)
    op.alter_column('operation_logs', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='工单ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_firewalls_id'), table_name='firewalls')
    op.alter_column('firewalls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('firewalls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('firewalls', 'is_active',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='是否启用(0:否, 1:是)',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('firewalls', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='状态',
               existing_comment='状态(enabled/disabled)',
               existing_server_default=sa.text("'enabled'::character varying"))
    op.alter_column('firewalls', 'allow_same_firewall_push',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               nullable=False,
               comment='是否允许同墙推送（源目的IP都在内部IP段时）',
               existing_comment='是否允许同墙推送（源目的IP都在内部IP段时）(0:否, 1:是)',
               existing_server_default=sa.text('false'))
    op.alter_column('firewalls', 'auto_push',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='是否支持自动推送',
               existing_comment='是否支持自动推送(0:否, 1:是)',
               existing_server_default=sa.text('1'))
    op.alter_column('firewalls', 'supported_policy_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='支持的策略类型',
               existing_comment='支持的策略类型数组',
               existing_nullable=True)
    op.alter_column('firewalls', 'external_protected_ips',
               existing_type=sa.TEXT(),
               comment='外部防护IP段',
               existing_comment='外部防护IP段，每行一个',
               existing_nullable=True)
    op.alter_column('firewalls', 'internal_protected_ips',
               existing_type=sa.TEXT(),
               comment='防护IP段',
               existing_comment='内部防护IP段，每行一个',
               existing_nullable=True)
    op.alter_column('firewalls', 'connection_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='连接配置',
               existing_comment='连接配置(根据type存不同结构)',
               existing_nullable=True)
    op.alter_column('firewalls', 'management_ip',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='管理IP',
               existing_nullable=False)
    op.alter_column('firewalls', 'type',
               existing_type=postgresql.ENUM('fortigate', 'hillstone', 'leadsec', 'h3c', 'guanqun', 'feita', 'wangshen', 'sangfor', 'huawei', 'shanshi', 'other', name='firewalltype'),
               comment=None,
               existing_comment='防火墙类型',
               existing_nullable=False)
    op.alter_column('firewalls', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='防火墙名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_zone_access_configs_id'), table_name='zone_access_configs')
    op.drop_table('zone_access_configs')
    # ### end Alembic commands ###
